### ISSUE TITLE
gcc failed with exit status 1

### ISSUE THREAD

**Issue by Glenn-zkl** [chanyn/Reasoning-RCNN#8]
when i run 'compils.sh' ,it goes with gcc failed with exit staus 1.
anyone come over this problem?

**Comment by Fran0K** [comment]
hi Glenn,I met this problem few days ago .here is my solutions and hope it can help you out

My error information :
`cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
src/deform_conv_cuda.cpp: In function 'void shape_check(at::Tensor, at::Tensor, at::Tensor*, at::Tensor, int, int, int, int, int, int, int, int, int, int)':
src/deform_conv_cuda.cpp:71:33: error: 'AT_CHECK' was not declared in this scope
              weight.ndimension());` 
It keeps repeating the `AT_CHECK`error and raises `error: command 'gcc' failed with exit status 1`at the end

Why:
 `AT_CHECK` is deprecated in pytorch version >=0.4(I know the code should be ran in pyotch 0.4 in author recommendation ,but i ran it in pytorch version =0.4 in docker ,it raise the same gcc error info(sad face here). then I decide to run the code in the pytorch version = 1.9) 

My solution:
Replaced `AT_CHECK` with `TORCH_CHECK` in the following files
`Reasoning-RCNN/mmdet/ops/roi_align/src/roi_align_cuda.cpp`
`Reasoning-RCNN/mmdet/ops/roi_pool/src/roi_pool_cuda.cpp`
`Reasoning-RCNN/mmdet/ops/dcn/src/deform_conv_cuda.cpp`
`Reasoning-RCNN/mmdet/ops/dcn/src/deform_pool_cuda.cpp`

run`./compile.sh`  and` 'gcc' failed with exit status 1` disappear at the end（btw My way work fine in pytorch = 1.9 in docker )

**Comment by QingtianK** [comment]
Hi Fran0K  and Glenn .Did you two run this code successfully?

**Comment by Glenn-zkl** [comment]
> Hi Fran0K and Glenn .Did you two run this code successfully?



> Hi Fran0K and Glenn .Did you two run this code successfully?

not yet,because i was trying to realize other method on my own baseline before now.
and now i am suffering from another problem that is how to generate a 'graph.pkl' used on my own dataset.
So,sir,do you know how to generate it? 
: )

**Comment by Glenn-zkl** [comment]
> hi Glenn,I met this problem few days ago .here is my solutions and hope it can help you out
> 
> My error information :
> `cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ src/deform_conv_cuda.cpp: In function 'void shape_check(at::Tensor, at::Tensor, at::Tensor*, at::Tensor, int, int, int, int, int, int, int, int, int, int)': src/deform_conv_cuda.cpp:71:33: error: 'AT_CHECK' was not declared in this scope weight.ndimension());`
> It keeps repeating the `AT_CHECK`error and raises `error: command 'gcc' failed with exit status 1`at the end
> 
> Why:
> `AT_CHECK` is deprecated in pytorch version >=0.4(I know the code should be ran in pyotch 0.4 in author recommendation ,but i ran it in pytorch version =0.4 in docker ,it raise the same gcc error info(sad face here). then I decide to run the code in the pytorch version = 1.9)
> 
> My solution:
> Replaced `AT_CHECK` with `TORCH_CHECK` in the following files
> `Reasoning-RCNN/mmdet/ops/roi_align/src/roi_align_cuda.cpp`
> `Reasoning-RCNN/mmdet/ops/roi_pool/src/roi_pool_cuda.cpp`
> `Reasoning-RCNN/mmdet/ops/dcn/src/deform_conv_cuda.cpp`
> `Reasoning-RCNN/mmdet/ops/dcn/src/deform_pool_cuda.cpp`
> 
> run`./compile.sh` and` 'gcc' failed with exit status 1` disappear at the end（btw My way work fine in pytorch = 1.9 in docker )

Thanks for your suggestion. ： ）
According to what you say , i guess you run it successfully. So, do you know how to generate the 'graph.pkl' ?  This is not interpreted in the paper.

**Comment by QingtianK** [comment]
> > Hi Fran0K and Glenn .Did you two run this code successfully?
> 
> > Hi Fran0K and Glenn .Did you two run this code successfully?
> 
> not yet,because i was trying to realize other method on my own baseline before now.
> and now i am suffering from another problem that is how to generate a 'graph.pkl' used on my own dataset.
> So,sir,do you know how to generate it?
> : )

Sorry，I have the same problem.
